version: "3"

services:
  fsproxy:
    #image: docker.io/galenguyer/fsproxy:latest
    build: .
    command:
      - "--upstream"
      - "https://example.com"
    ports:
      - "127.0.0.1:6969:6969"
